### ISSUE TITLE
cursor path and statistics before target appearance

### ISSUE THREAD

**Issue by PhilippWanner** [ssciwr/motor-task-prototype#150]
Adding an option that allows to show cursor path before target appearance and to measure cursor movement/calculate outcome parameters:
- At the moment, there is the option that allows to move the cursor before target appearance (deselecting option “freeze cursor until target is displayed”). However, the cursor path of the movement before target appearance is not displayed and the statistics/outcome parameters are not calculated for this movement/time. In some cases/experiments we would like to collect the cursor path and statistics of the movement before target appearance. For example, the participants are instructed to learn a fixed sequence (e.g. a sequence of 8 targets over 200 repetitions) and we want to measure if the participants can anticipate the target location (i.e. movement to the target takes place before the target is displayed). Therefore, an option that allows to display/measure the cursor path and calculate statistics including the movement before target appearance would be great. In this case, the calculation of the statistics would be similar. However, the “reaction time to target” would be negative if the participants moves the cursor before target appearance and positive if the cursor is moved after target appearance.

**Comment by lkeegan** [comment]
(2nd priority)
