### ISSUE TITLE
Trials/blocks without central target

### ISSUE THREAD

**Issue by PhilippWanner** [ssciwr/motor-task-prototype#153]
Adding an option that allows to define trials/blocks without reaching the central target:
- At the moment, there is only the option that after the target was reached the central targets have to be reached (i.e. out and back movements from a central starting point to one of the targets and back to the central target). An option that allows to define trials/blocks without the central target would be great (e.g. after a target was reached a next target have to be reached and not the central target)

**Comment by lkeegan** [comment]
(5th priority)
Ideally they would start at the first target of the sequence, if not can start in the center
